#!/usr/bin/env python3
"""(Re)build data/sequences/index.json — the app's sequence discovery file.

The app never hardcodes program names: it loads index.json and offers every
sequence listed there. Drop a new <id>.json into data/sequences/ (or compile
one with scripts/new_sequence.py), rerun this, done — the program appears in
the picker.

Usage:
    python3 scripts/build_sequence_index.py           # rebuild index.json
    python3 scripts/build_sequence_index.py --check   # CI: fail if stale
"""
import glob, json, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SEQ_DIR = os.path.join(ROOT, "data/sequences")
INDEX = os.path.join(SEQ_DIR, "index.json")


def build():
    entries = []
    for path in sorted(glob.glob(os.path.join(SEQ_DIR, "*.json"))):
        if os.path.basename(path) == "index.json":
            continue
        with open(path, encoding="utf-8") as f:
            seq = json.load(f)
        if "id" not in seq or "units" not in seq:
            continue  # not a sequence file
        entries.append({
            "id": seq["id"],
            "name": seq.get("name", seq["id"]),
            "region": seq.get("region", ""),
            "native_view": seq.get("native_view", "grapheme_first"),
            "units": len(seq["units"]),
            "gpcs": sum(len(u.get("teaches", [])) for u in seq["units"]),
            "approximate": bool(seq.get("accuracy_note")),
            "file": os.path.basename(path),
        })
    entries.sort(key=lambda e: e["name"].lower())
    return {"comment": "GENERATED by scripts/build_sequence_index.py — do not edit by hand.",
            "sequences": entries}


def main():
    index = build()
    new_text = json.dumps(index, ensure_ascii=False, indent=2) + "\n"
    if "--check" in sys.argv:
        try:
            with open(INDEX, encoding="utf-8") as f:
                old_text = f.read()
        except FileNotFoundError:
            old_text = ""
        if old_text != new_text:
            print("ERROR: data/sequences/index.json is stale — "
                  "run python3 scripts/build_sequence_index.py and commit it.")
            sys.exit(1)
        print(f"index.json up to date ({len(index['sequences'])} sequences)")
        return
    with open(INDEX, "w", encoding="utf-8") as f:
        f.write(new_text)
    print(f"Wrote data/sequences/index.json ({len(index['sequences'])} sequences):")
    for e in index["sequences"]:
        approx = " (approximate)" if e["approximate"] else ""
        print(f"  {e['id']:28s} {e['units']:3d} units  {e['region']:5s} {e['native_view']}{approx}")


if __name__ == "__main__":
    main()
